{application,websocket_demo,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{websocket_demo_app,[]}},
              {env,[]},
              {modules,[websocket_demo,websocket_demo_app,
                        websocket_demo_sup]}]}.
